#!/usr/bin/env bash
#
# Re-mint tests/fixtures/module-edge-conditions/frozen-0.27.0-baseline.json.
#
# That fixture is a baseline generated by **v0.27.0 code** — the release before the
# module-edge widening — and `tests/helpers/module-edge-migration.test.ts` replays it
# to prove the migration promise: every pre-existing `import` finding keeps its
# identity, and every new-kind finding is reported as new.
#
# It must NOT be generated by the current build. A baseline made here would encode
# whatever message this build produces, so "the import messages are unchanged" would
# be true by construction and the test would pass however far the text moved.
#
# Any edit to a `module-edge-conditions` fixture changes the finding set and
# invalidates it. This script is the reproducible way back; without it the procedure
# is folklore.
set -euo pipefail

TAG="${FROZEN_TAG:-v0.27.0}"
REPO="$(git rev-parse --show-toplevel)"
FIXTURE="tests/fixtures/module-edge-conditions"
WORKTREE="$(mktemp -d)/frozen-${TAG}"

cleanup() { git -C "$REPO" worktree remove --force "$WORKTREE" 2>/dev/null || true; }
trap cleanup EXIT

echo "Regenerating from ${TAG} …"
git -C "$REPO" worktree add -q --detach "$WORKTREE" "$TAG"
# The fixture must be TODAY's, run through the OLD code — that is the whole point.
cp -R "$REPO/$FIXTURE" "$WORKTREE/tests/fixtures/"
ln -s "$REPO/node_modules" "$WORKTREE/node_modules"

cat > "$WORKTREE/regen.ts" <<'GEN'
import path from 'node:path'
import { modules, project } from './src/index.js'
import { generateBaseline } from './src/helpers/baseline.js'
const root = path.resolve('tests/fixtures/module-edge-conditions')
const p = project(path.join(root, 'tsconfig.json'))
const found = modules(p).should().notImportFrom('**/banned/**').violations()
console.log(`findings at this tag: ${found.length}`)
for (const v of found) console.log(`  ${path.basename(v.file)}:${v.line}`)
generateBaseline(found, path.join(root, 'frozen-0.27.0-baseline.json'), { root })
GEN

(cd "$WORKTREE" && npx tsx regen.ts)
cp "$WORKTREE/$FIXTURE/frozen-0.27.0-baseline.json" "$REPO/$FIXTURE/"
echo
echo "Written. Now update the counts in tests/helpers/module-edge-migration.test.ts:"
python3 -c "
import json,sys
d=json.load(open('$REPO/$FIXTURE/frozen-0.27.0-baseline.json'))
print(f'  frozen entries: {d[\"count\"]}')
for v in d['violations']: print(f'    {v[\"file\"]}:{v[\"line\"]}')"
