import type { RuleDescription } from '../../core/rule-description.js'
import { loadRuleFiles } from '../load-rules.js'

export interface ExplainArgs {
  ruleFiles: string[]
  markdown?: boolean
  /** Explain output format: 'json' (default), 'markdown', or 'agent'. */
  format?: string
}

interface Describable {
  describeRule(): RuleDescription
}

function isDescribable(value: unknown): value is Describable {
  return (
    value !== null &&
    value !== undefined &&
    typeof value === 'object' &&
    'describeRule' in value &&
    typeof (value as Record<string, unknown>)['describeRule'] === 'function'
  )
}

/**
 * Dump all active rules as structured JSON or markdown.
 */
export async function runExplain(args: ExplainArgs): Promise<void> {
  const builders = await loadRuleFiles(args.ruleFiles)

  const descriptions: RuleDescription[] = []
  for (const builder of builders) {
    if (isDescribable(builder)) {
      descriptions.push(builder.describeRule())
    }
  }

  if (args.format === 'agent') {
    outputAgent(descriptions)
  } else if (args.markdown || args.format === 'markdown') {
    outputMarkdown(descriptions)
  } else {
    outputJson(descriptions)
  }
}

const AGENT_START = '<!-- ts-archunit:start -->'
const AGENT_END = '<!-- ts-archunit:end -->'

/**
 * Emit imperative markdown for an AI-agent system prompt / project instructions.
 * The block is wrapped in sentinel markers so tooling can replace it idempotently.
 */
function outputAgent(descriptions: RuleDescription[]): void {
  const lines: string[] = [
    AGENT_START,
    '',
    '## Architecture Rules (auto-generated by ts-archunit)',
    '',
    'The following rules are enforced by CI. Violations will block your PR.',
    '',
    '**Verify before you continue:** after writing or changing code, run ' +
      '`npx ts-archunit check --format json`, read the `violations` array, and fix ' +
      'each one using its `suggestion`. Do this in your edit loop — do not wait for CI.',
    '',
  ]

  if (descriptions.length === 0) {
    lines.push('_No rules found._', '', AGENT_END)
    process.stdout.write(lines.join('\n') + '\n')
    return
  }

  // Group by the rule id's first namespace segment (e.g. `preset/agent/...` →
  // "preset"), or "General" for rules without an id.
  const groups = new Map<string, RuleDescription[]>()
  for (const d of descriptions) {
    const key = d.id ? (d.id.split('/')[0] ?? 'General') : 'General'
    const group = groups.get(key) ?? []
    group.push(d)
    groups.set(key, group)
  }

  for (const [group, rules] of groups) {
    lines.push(`### ${titleCase(group)}`, '')
    for (const d of rules) {
      const imperative = d.imperative ?? (d.rule || 'Follow the architecture rule.')
      const because = d.because ? ` — ${d.because}` : ''
      lines.push(`- ${imperative}${because}`)
    }
    lines.push('')
  }

  lines.push(AGENT_END)
  process.stdout.write(lines.join('\n') + '\n')
}

function titleCase(s: string): string {
  return s.length === 0 ? s : s[0]!.toUpperCase() + s.slice(1)
}

function outputJson(descriptions: RuleDescription[]): void {
  const output = {
    rules: descriptions,
    generatedAt: new Date().toISOString(),
  }
  process.stdout.write(JSON.stringify(output, null, 2) + '\n')
}

function outputMarkdown(descriptions: RuleDescription[]): void {
  if (descriptions.length === 0) {
    process.stdout.write('No rules found.\n')
    return
  }

  process.stdout.write('| ID | Rule | Because | Suggestion |\n')
  process.stdout.write('|----|------|---------|------------|\n')
  for (const d of descriptions) {
    const id = d.id ?? '-'
    const rule = d.rule || '-'
    const because = d.because ?? '-'
    const suggestion = d.suggestion ?? '-'
    process.stdout.write(`| ${id} | ${rule} | ${because} | ${suggestion} |\n`)
  }
}
