/**
 * The migration promise, and the remedies — plan 0071 test-inventory items 11
 * and 13.
 *
 * §4's claim is that a consumer who refreshes their baseline on 0.27.x and then
 * upgrades sees **only** what the widening added. That rests on two things this
 * file pins: every pre-existing `import` finding keeps its identity, and every
 * new-kind finding gets a distinct one so it is not absorbed by an existing
 * entry for the same module.
 */
import { describe, it, expect } from 'vitest'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { Project, ts } from 'ts-morph'
import { modules, project } from '../../src/index.js'
import { generateBaseline, withBaseline } from '../../src/helpers/baseline.js'
import { edgesOf } from '../../src/core/module-edges.js'

const fixtureRoot = path.join(import.meta.dirname, '../fixtures/module-edge-conditions')
const frozen = path.join(fixtureRoot, 'frozen-0.27.0-baseline.json')
const p = project(path.join(fixtureRoot, 'tsconfig.json'))
const BANNED = '**/banned/**'

describe('item 13 — a frozen 0.27.0 baseline, after bug 0028 moved identity', () => {
  /**
   * The committed baseline was generated by **v0.27.0 code**, in a detached
   * worktree at that tag, not by this build filtered down to the static findings.
   *
   * Re-mint it with `scripts/regen-frozen-baseline.sh` after any change to a
   * `module-edge-conditions` fixture — that changes the finding set and invalidates
   * these hashes. The script exists because the procedure is otherwise folklore:
   * it needs a v0.27.0 worktree with *today's* fixture copied into it.
   *
   * That matters: a baseline generated here would encode whatever message this
   * build produces, so "the import messages are unchanged" would be true by
   * construction and the test would pass however much the text moved. Reading it
   * from the released version's own output is what makes it a check rather than a
   * restatement.
   */
  it('was written by v0.27.0 and contains only the static-import findings', () => {
    const parsed: unknown = JSON.parse(fs.readFileSync(frozen, 'utf-8'))
    expect(parsed).toMatchObject({ count: 5, hashVersion: 2 })
  })

  /**
   * **This release invalidates it, deliberately.**
   *
   * Bug 0028 gave dependency findings a producer-set `identity`, which replaces
   * `element::message` in the hash — so every dependency finding's identity changed,
   * not only the colliding ones. No printed text moved, which is exactly why the bug
   * first recorded this as needing no migration treatment: that conflated
   * text-stability with baseline-stability and was wrong.
   *
   * So the property this used to pin — a v0.27.0 baseline absorbing the static
   * findings byte-for-byte — is now historical. What is worth guarding is the cost
   * itself: that the old baseline stops matching, and that the run says why rather
   * than reporting 14 findings as if they were all new work.
   */
  it('no longer absorbs anything, and that is the migration cost', () => {
    const all = modules(p).should().notImportFrom(BANNED).violations()
    const fresh = withBaseline(frozen, { root: fixtureRoot }).filterNew(all)

    // Every finding reads as new, because every identity changed…
    for (const v of all) {
      expect(fresh.some((f) => f.message === v.message && f.line === v.line)).toBe(true)
    }
    // …and the run does not leave that unexplained. `filterNew` adds one diagnostic
    // when a non-empty baseline matches nothing at all, so `fresh` is one longer than
    // `all` — that extra entry IS the explanation, and it is the difference between a
    // silent invalidation and a stated one.
    expect(fresh).toHaveLength(all.length + 1)
    const diagnostic = fresh.find((f) => !all.some((v) => v.message === f.message))
    expect(diagnostic?.message).toMatch(/baseline/i)
    expect(diagnostic?.bypassFilters).toBe(true)

    // Non-vacuity: an empty run would satisfy the loop above.
    expect(all.length).toBeGreaterThan(10)
  })

  /**
   * The forward-looking half: a baseline written by the CURRENT code replays with
   * nothing new.
   *
   * That is the property a consumer actually depends on after they refresh, and it is
   * what the v0.27.0 fixture used to provide before this release moved identity. It
   * needs no committed fixture — generating and replaying in one test is the whole
   * point, since the two halves must agree with each other rather than with a
   * snapshot.
   */
  it('a baseline written now replays with zero new findings', () => {
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'ts-archunit-0028-'))
    const file = path.join(dir, 'baseline.json')
    try {
      const all = modules(p).should().notImportFrom(BANNED).violations()
      generateBaseline(all, file, { root: fixtureRoot })

      const fresh = withBaseline(file, { root: fixtureRoot }).filterNew(all)
      expect(fresh).toEqual([])
      // Non-vacuity: an empty run would satisfy the line above.
      expect(all.length).toBeGreaterThan(10)
    } finally {
      fs.rmSync(dir, { recursive: true, force: true })
    }
  })
})

describe('item 11 — each new kind`s remedy actually remediates', () => {
  /**
   * Applied to an **in-memory** copy (`project.createSourceFile`), per the plan's
   * note: editing a committed fixture in place makes the test order-dependent
   * under a parallel runner, and leaves the repo dirty when it fails.
   *
   * "Distinctness is not honesty" is the point of this item. A per-kind verb makes
   * two findings *different*; it does not make either one *followable*.
   */
  const applyAndRecheck = (source: string): number => {
    const scratch = new Project({
      compilerOptions: {
        // Named enums, not literals. `moduleResolution: 3` is the dangerous one:
        // `ModuleResolutionKind`'s numbering has churned across TS versions
        // (`Node16`/`NodeNext`/`Bundler` were added later, `NodeJs` became `Node10`),
        // so it is a value that silently means something else on a toolchain move.
        target: ts.ScriptTarget.ESNext,
        module: ts.ModuleKind.Node16,
        moduleResolution: ts.ModuleResolutionKind.Node16,
        strict: true,
        noEmit: true,
      },
    })
    scratch.createSourceFile(
      '/src/banned/secret.ts',
      'export const SECRET = 1\nexport type S = { a: 1 }\n',
    )
    scratch.createSourceFile(
      '/src/allowed/ok.ts',
      'export const OK = 1\nexport type O = { b: 1 }\n',
    )
    const subject = scratch.createSourceFile('/src/subject.ts', source)
    // `edgesOf` rather than a full rule run: the remedy has to remove the EDGE,
    // and asserting on the edge is what makes "it remediates" specific.
    return edgesOf(subject).filter(
      (e) => e.resolvedPath?.includes('/banned/') === true && !e.typeOnly,
    ).length
  }

  it('the re-export remedy — `export type` — removes the runtime edge', () => {
    // Before: a runtime re-export of a banned module.
    expect(applyAndRecheck(`export { SECRET } from './banned/secret.js'\n`)).toBe(1)
    // After following the stated remedy. It erases the dependency — and removes a
    // runtime export, which is why the remedy text says to check consumers.
    expect(applyAndRecheck(`export type { S } from './banned/secret.js'\n`)).toBe(0)
  })

  it('the re-export remedy`s alternative — re-export from a permitted module — also clears it', () => {
    // The remedy offers this precisely because `export type` changes what the
    // module publishes: if a consumer needs the value, moving the source is the
    // fix that keeps the runtime export.
    expect(applyAndRecheck(`export { OK } from './allowed/ok.js'\n`)).toBe(0)
  })

  it('the dynamic-import remedy is honest that erasure is unavailable', () => {
    // `import type` cannot be applied to `await import(…)`, so the remedy moves
    // the dependency instead. Following the erasure advice here would be
    // impossible, which is why `dynamic` is excluded from
    // onlyHaveTypeImportsFrom entirely.
    expect(applyAndRecheck(`export const load = () => import('./banned/secret.js')\n`)).toBe(1)
    expect(applyAndRecheck(`export const load = () => import('./allowed/ok.js')\n`)).toBe(0)
  })

  it('a type expression is already erased, so its remedy is "no change needed"', () => {
    // Asserted so the remedy text cannot drift into advising an edit that would do
    // nothing: the edge carries `typeOnly: true` and no runtime dependency exists
    // to remove.
    const edges = (() => {
      const scratch = new Project({
        compilerOptions: {
          target: ts.ScriptTarget.ESNext,
          module: ts.ModuleKind.Node16,
          moduleResolution: ts.ModuleResolutionKind.Node16,
          strict: true,
          noEmit: true,
        },
      })
      scratch.createSourceFile('/src/banned/secret.ts', 'export type S = { a: 1 }\n')
      const subject = scratch.createSourceFile(
        '/src/subject.ts',
        `export type B = import('./banned/secret.js').S\n`,
      )
      return edgesOf(subject)
    })()

    expect(edges).toHaveLength(1)
    expect(edges[0]?.kind).toBe('type-expression')
    expect(edges[0]?.typeOnly).toBe(true)
  })
})
