/**
 * The migration promise, and the remedies — plan 0071 test-inventory items 11
 * and 13.
 *
 * §4's claim is that a consumer who refreshes their baseline on 0.27.x and then
 * upgrades sees **only** what the widening added. That rests on two things this
 * file pins: every pre-existing `import` finding keeps its identity, and every
 * new-kind finding gets a distinct one so it is not absorbed by an existing
 * entry for the same module.
 */
import { describe, it, expect } from 'vitest'
import fs from 'node:fs'
import path from 'node:path'
import { Project } from 'ts-morph'
import { modules, project } from '../../src/index.js'
import { withBaseline } from '../../src/helpers/baseline.js'
import { edgesOf } from '../../src/core/module-edges.js'

const fixtureRoot = path.join(import.meta.dirname, '../fixtures/module-edge-conditions')
const frozen = path.join(fixtureRoot, 'frozen-0.27.0-baseline.json')
const p = project(path.join(fixtureRoot, 'tsconfig.json'))
const BANNED = '**/banned/**'

describe('item 13 — a frozen 0.27.0 baseline replays correctly', () => {
  /**
   * The committed baseline was generated by **v0.27.0 code**, in a detached
   * worktree at that tag, not by this build filtered down to the static findings.
   *
   * That matters: a baseline generated here would encode whatever message this
   * build produces, so "the import messages are unchanged" would be true by
   * construction and the test would pass however much the text moved. Reading it
   * from the released version's own output is what makes it a check rather than a
   * restatement.
   */
  it('was written by v0.27.0 and contains only the static-import findings', () => {
    const parsed: unknown = JSON.parse(fs.readFileSync(frozen, 'utf-8'))
    expect(parsed).toMatchObject({ count: 4, hashVersion: 2 })
  })

  it('absorbs every pre-existing import finding and reports the new kinds as new', () => {
    const all = modules(p).should().notImportFrom(BANNED).violations()
    const baseline = withBaseline(frozen, { root: fixtureRoot })
    const fresh = baseline.filterNew(all)

    // The whole run, then the delta. 12 total, 4 already accepted, 8 new.
    expect(all).toHaveLength(12)
    expect(fresh).toHaveLength(8)

    const newIdentities = fresh
      .map((v) => `${path.relative(fixtureRoot, v.file)}:${String(v.line)}`)
      .sort((a, b) => a.localeCompare(b))
    expect(newIdentities).toEqual([
      'src/consumer-dynamic.ts:2',
      'src/consumer-reexport-type.ts:2',
      'src/consumer-reexport.ts:3',
      'src/consumer-star.ts:2',
      'src/consumer-type-expr.ts:2',
      'src/mixed.ts:5',
      'src/twice.ts:4',
      'src/twice.ts:5',
    ])
    // The four the baseline accounts for are exactly the static imports, and NOT
    // the re-export on the adjacent line of the same file.
    expect(newIdentities).not.toContain('src/consumer-import.ts:1')
    expect(newIdentities).not.toContain('src/mixed.ts:4')
    expect(newIdentities).not.toContain('src/imports-twice.ts:5')
    expect(newIdentities).not.toContain('src/imports-twice.ts:6')
  })

  /**
   * `mixed.ts` is the shape §4 exists for: one file that both imports and
   * re-exports the same banned module. Without per-kind verbs the two findings are
   * byte-identical, so the re-export hashes to the import's frozen entry, is
   * filtered as already-accepted, and is **never reported at all** — a finding
   * silently absorbed by a baseline written before it could exist.
   */
  it('reports the re-export in mixed.ts as new, which a shared verb would absorb', () => {
    // The SAME rule shape the frozen baseline was generated from — no `.that()`.
    // `hashViolation` is `rule::element::message`, so adding a predicate changes
    // the rule description and therefore every identity, and the baseline would
    // match nothing for a reason that has nothing to do with the widening. Filter
    // to the file after the run instead.
    const fresh = withBaseline(frozen, { root: fixtureRoot })
      .filterNew(modules(p).should().notImportFrom(BANNED).violations())
      .filter((v) => v.file.endsWith('mixed.ts'))

    expect(fresh).toHaveLength(1)
    expect(fresh[0]?.line).toBe(5)
    expect(fresh[0]?.message).toContain('re-exports')
  })
})

describe('item 11 — each new kind`s remedy actually remediates', () => {
  /**
   * Applied to an **in-memory** copy (`project.createSourceFile`), per the plan's
   * note: editing a committed fixture in place makes the test order-dependent
   * under a parallel runner, and leaves the repo dirty when it fails.
   *
   * "Distinctness is not honesty" is the point of this item. A per-kind verb makes
   * two findings *different*; it does not make either one *followable*.
   */
  const applyAndRecheck = (source: string): number => {
    const scratch = new Project({
      compilerOptions: {
        target: 99,
        module: 100,
        moduleResolution: 3,
        strict: true,
        noEmit: true,
      },
    })
    scratch.createSourceFile(
      '/src/banned/secret.ts',
      'export const SECRET = 1\nexport type S = { a: 1 }\n',
    )
    scratch.createSourceFile(
      '/src/allowed/ok.ts',
      'export const OK = 1\nexport type O = { b: 1 }\n',
    )
    const subject = scratch.createSourceFile('/src/subject.ts', source)
    // `edgesOf` rather than a full rule run: the remedy has to remove the EDGE,
    // and asserting on the edge is what makes "it remediates" specific.
    return edgesOf(subject).filter(
      (e) => e.resolvedPath?.includes('/banned/') === true && !e.typeOnly,
    ).length
  }

  it('the re-export remedy — `export type` — removes the runtime edge', () => {
    // Before: a runtime re-export of a banned module.
    expect(applyAndRecheck(`export { SECRET } from './banned/secret.js'\n`)).toBe(1)
    // After following the stated remedy. It erases the dependency — and removes a
    // runtime export, which is why the remedy text says to check consumers.
    expect(applyAndRecheck(`export type { S } from './banned/secret.js'\n`)).toBe(0)
  })

  it('the re-export remedy`s alternative — re-export from a permitted module — also clears it', () => {
    // The remedy offers this precisely because `export type` changes what the
    // module publishes: if a consumer needs the value, moving the source is the
    // fix that keeps the runtime export.
    expect(applyAndRecheck(`export { OK } from './allowed/ok.js'\n`)).toBe(0)
  })

  it('the dynamic-import remedy is honest that erasure is unavailable', () => {
    // `import type` cannot be applied to `await import(…)`, so the remedy moves
    // the dependency instead. Following the erasure advice here would be
    // impossible, which is why `dynamic` is excluded from
    // onlyHaveTypeImportsFrom entirely.
    expect(applyAndRecheck(`export const load = () => import('./banned/secret.js')\n`)).toBe(1)
    expect(applyAndRecheck(`export const load = () => import('./allowed/ok.js')\n`)).toBe(0)
  })

  it('a type expression is already erased, so its remedy is "no change needed"', () => {
    // Asserted so the remedy text cannot drift into advising an edit that would do
    // nothing: the edge carries `typeOnly: true` and no runtime dependency exists
    // to remove.
    const edges = (() => {
      const scratch = new Project({
        compilerOptions: { target: 99, module: 100, moduleResolution: 3, strict: true },
      })
      scratch.createSourceFile('/src/banned/secret.ts', 'export type S = { a: 1 }\n')
      const subject = scratch.createSourceFile(
        '/src/subject.ts',
        `export type B = import('./banned/secret.js').S\n`,
      )
      return edgesOf(subject)
    })()

    expect(edges).toHaveLength(1)
    expect(edges[0]?.kind).toBe('type-expression')
    expect(edges[0]?.typeOnly).toBe(true)
  })
})
